### ISSUE TITLE
django 연습코드 구동시키기

### ISSUE THREAD

**Issue by kimsunoh** [pro00er/projobsearcher_frontend#2]
## Description
- 2018.08.10 @ohahohah @kimsunoh가 한 practice 코드가 'hostname/heyheyhey'에 접근 할 수 있도록 수정이 필요함
- 2018.08.20까지 수정 후 PR 날리기

## CheckList
- [x] issue를 한눈에 파악 할 수 있게 issue title은 작성되었는가? 
- [x] assignees , labels 확인하기 
- [x] issue body는 issue body만 확인하고도 모르는 사람도 내용을 파악할 수 있을 정도로 적었는가? (무엇을,언제,어디서)

**Comment by syohnet** [comment]
@kimsunoh 관련 리포지토리가 달라서 https://github.com/pro00er/projobsearcher_scraping_learning/issues/12 로 옮겨 적었습니다.
